import { Geist, Manrope } from "next/font/google";
import "./globals.css";
import Sidebar from "./(components)/sidebar/sidebar";

const geistSans = Geist({
  variable: "--font-heading",
});

const manrope = Manrope({
  variable: "--font-body",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${geistSans.variable} ${manrope.variable}`}>
      <body>
        <Sidebar />
        {children}
      </body>
    </html>
  );
}
